### ISSUE TITLE
directory structure violates PhET convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#1]
Source-code directory structure for a 1-screen sim should look like this:

``` js
js/
 atomic-interactions/
    model/
    view/
```

**Comment by jbphet** [comment]
This was fixed locally (see commits above) and then the code was moved into the states-of-matter repository (see #15 and https://github.com/phetsims/states-of-matter/issues/48), so all should now be in accordance with our current policies for directory structure and resource location.  Closing.
