### ISSUE TITLE
Appearance of the graph does not match design spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#10]
The image below shows the current sim (at 1024 x 670 aspect ratio) on top, aligned with a copy of the design spec at the same size overlaid on it (at the bottom), for comparison:
 ![screen shot 2015-02-25 at 8 40 21 pm](https://cloud.githubusercontent.com/assets/4682895/6385955/cf0113cc-bd2e-11e4-8296-ff3640e64544.png)

Please adjust the graph to better match the design as follows:
- [x] Decrease the width of the graph (keeping it aligned roughly with the current right-edge)
- [x] Decrease the height of the graph (without moving the bottom edge)
- [x] Increase the transparency of the gridlines
- [x] Increase the font size for the sigma and epsilon symbols
- [x] Slightly decrease the size of both zoom buttons
- [x] Remove thicker grey horizontal line which is overlaid on the 'zero' of the graph (i.e. the middle gridline should be the same appearance as all the other gridlines)
- [x] Re-align the pinned atom to the new left edge of the graph

**Comment by jbphet** [comment]
Is this ready for verification?  I just published Looks like this may have been fixed.  Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html, which includes the latest commit, so if this is fixed the issue should be assigned to @ycarpenterphet.

**Comment by pixelzoom** [comment]
Looks like the commit above introduced a layout problem with the 'Oxygen Oxygen' radio button layout, see this screenshot:

![screenshot_224](https://cloud.githubusercontent.com/assets/3046552/6406057/caed94d0-bde8-11e4-9365-237e4d43773e.png)

**Comment by ycarpenterphet** [comment]
It looks like a few issues have been solved (checked off in the list above), but a few remain.
- [x] The size of the graph has been fixed, but the alignment is incorrect - it needs to be moved down and to the right to match the spec shown.
- [x] The grey horizontal line in the center of the graph is still thicker than the other gridlines. It should look identical to any other gridline.

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar so that she's in the loop on this one for states of matter too)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Getting closer, but still a few changes in order to match the mockup.

(1) The new alignment of the graph requires that the atoms be moved as well to match the design spec, since the center of the pinned atom should align with the left edge/axis of the graph in the mockup, and the center of the moveable atom should be aligned with the moving dot on the graph, just like in the Java sim and mockups.

(2) The zoom buttons are located slightly further up and to the right, placing them closer to the graph axis in the mockup and almost in line with the top of the arrow at the end of the axis.

(3) Increase the font size of sigma and epsilon slightly more to match mockup.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks great, thanks. Closing.
