### ISSUE TITLE
When the curve on the graph extends below the x-axis, epsilon arrow should not be double-headed

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#11]
From the design doc: 
![screen shot 2015-02-25 at 9 05 09 pm](https://cloud.githubusercontent.com/assets/4682895/6386169/0547e520-bd32-11e4-8e55-905b492b11b2.png)

On the vertical line labelled with an epsilon symbol, there should be an arrow only at the top end when the curve itself is hidden below the distance axis. The bottom arrowhead only appears when the bottom of the curve is visible.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code.Assigning to @ycarpenterphet  for verification.

**Comment by ycarpenterphet** [comment]
Looks good - closed.
