### ISSUE TITLE
Return Atom button should not appear until atom leaves screen area

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#12]
Currently, the Return Atom button becomes visible as soon as the center of the atom leave the dev area:
![screen shot 2015-02-25 at 10 26 43 pm](https://cloud.githubusercontent.com/assets/4682895/6386842/8a3593a8-bd3d-11e4-9fd4-c21e214e3c16.png)

Is it possible for the button to only appear after the center of the atom exits the browser window?

**Comment by jbphet** [comment]
Looks like this may have been fixed.  Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html.

**Comment by ycarpenterphet** [comment]
The Return Atom button should appear after the <i>center</i> of the atom leaves the browser area (it should not require the whole atom to be out of view).

Also, the current behaviour seems to be a bit buggy. 

<b>On a desktop: </b>
If I resize the browser window to the width of the dev area, I can drag the atom beyond the right edge of the screen without the return atom button appearing. 
![screen shot 2015-03-02 at 3 39 24 pm](https://cloud.githubusercontent.com/assets/4682895/6452344/57103a24-c0f2-11e4-93f3-46153682fa91.png)

If I then increase the width of my browser window, I can now see the atom sitting in the window.
![screen shot 2015-03-02 at 3 40 10 pm](https://cloud.githubusercontent.com/assets/4682895/6452363/7749faf0-c0f2-11e4-851f-1abd27168572.png)

<b>On a tablet: </b>
I can drag the atom all the way to the right edge of the screen, so that only the very edge of the atom is visible. After I let go, I cannot 'grab' the atom again, but the Return Atom button is not visible either. Reset is the only option to retrieve the atom.

**Comment by ycarpenterphet** [comment]
(also tagging @arouinfar since the outcome will affect https://github.com/phetsims/states-of-matter/)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks fixed. Closing.
