### ISSUE TITLE
Placement and size of Return Atom button does not match spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#13]
Design spec shows the following:
![screen shot 2015-02-25 at 10 36 46 pm](https://cloud.githubusercontent.com/assets/4682895/6386918/f17249b6-bd3e-11e4-8773-d7bde8fed0d6.png)

Please...
(1) Increase the font size of the 'Return Atom' label to match spec (should be the same size as the axis labels of the graph), and increase the button size to fit.
(2) Align the left-edge of the button with the left edge of the pinned atom, as shown.

**Comment by jbphet** [comment]
Looks like this may have been fixed.  Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html.

**Comment by ycarpenterphet** [comment]
Looks fine. Closing.
