### ISSUE TITLE
test i18n

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#16]
Because of issues like https://github.com/phetsims/atomic-interactions/issues/6 and #17, I don't think this sim has been tested for i18n compliance.

**Comment by ycarpenterphet** [comment]
Based on the i18n reports @pixelzoom made for the graph, I don't know if any of the recommended text translation handling specifications in the design doc were followed (see https://docs.google.com/document/d/1-2v8rQlwgWwqinYYiFu8PBIpRU7HL_InBIAtwpSzBMY/edit#heading=h.lw6yts2lgvdt)

Granted, I don't know if those are the best solutions in all cases (I think we'll still have i18n issues for the two column layout in the atom selection menu), but if any of them are viable suggested ways to handle the translation issue, we might want to refer back to them.

**Comment by pixelzoom** [comment]
i18n can be tested using the 'stringTest' query parameter, described in chipper.initialize-globals.js:

``` js
* stringTest - if set to "double", duplicates all of the translated strings which will allow to see (a) if all strings
 *                  are translated and (b) whether the layout can accommodate longer strings from other languages.
 *                  Note this is a heuristic rule that does not cover all cases.
 *            - if set to "none" or omitted, then the normal translated string will be shown
 *            - if set to anything else, it will use that string everywhere.  This will allow testing specific cases, like
 *                  whether the word 'vitesse' would substitute for 'speed' well.  Also, using "%20" it will show whitespace for all
 *                  of the strings, making it easy to identify non-translated strings

```

**Comment by pixelzoom** [comment]
You may need a new dev version to use the stringTest query parameter, since it was added very recently.

**Comment by jbphet** [comment]
v1.0.0-dev.3 supports the "stringTest" query param, see http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.3/atomic-interactions_en.html.

**Comment by ycarpenterphet** [comment]
As of dev6, this is what the sim looks like when string lengths are doubled:
![screen shot 2015-03-15 at 1 55 40 pm](https://cloud.githubusercontent.com/assets/4682895/6657764/1671f0ec-cb1b-11e4-9f61-18b81604025e.png)

These strings look ok:
Horizontal axis label (Distance between atoms)
Speed controls (Normal/Slow Motion)
Sim title in the navbar

None of the other strings seem to handle i18n, either in following with the design doc or in a way that avoids overlapping sim components.

**Comment by jbphet** [comment]
Just tested this on the current master version and it looks like the scaling is implemented and working.  Note that this approach results in mismatched fonts for long strings, but that is unavoidable when scaling is done.  The screenshot below illustrates.  Assigning back to @ycarpenterphet to decide whether this needs any more attention.  If not, she can close.

![ai-doubled-strings](https://cloud.githubusercontent.com/assets/3082831/6754967/964dfe64-cee5-11e4-8156-5730fbb952e4.png)

**Comment by ycarpenterphet** [comment]
I am ok with the mismatch in font sizes due the the variation in string length, but the scaling parameter choices are not very good in some cases, making the text much smaller than is necessary to fit.

For example, the weak/strong labels on the slider have plenty of space to expand horizontally before the text size is reduced. Same for the Atom Diameter and Interaction Strength labels.

In the forces menu, the arrows can be pushed to the right to allow for readable fonts to be used, but even the "Hide Forces" text seems to be scaled smaller than necessary to fit

![screenshot 2015-04-16 12 19 54](https://cloud.githubusercontent.com/assets/4682895/7188160/072320f8-e433-11e4-8367-1694c3f8cfaf.png)

Re-assigning @ChandrashekarBemagoni to adjust the scaling on these menu labels.

**Comment by ycarpenterphet** [comment]
@ChandrashekarBemagoni Can you comment on progress with resolving the remaining translation handling issues?

**Comment by ChandrashekarBemagoni** [comment]
In Hslider there is no option for aligning the label w.r.t the tick. Currently, text always center aligns on the tick.
Increasing the text scale factor increases the panel width as well and that leads to alignment mismatch between the top and bottom panels.

A better solution will probably be to add label alignment options to HSlider. 
@jbphet what do you think?

**Comment by jbphet** [comment]
Having such an option for HSlider seems like a good possibility.  Since this would be a common code change, PhET will need to take it on.  Reassigning to @ycarpenterphet to see if she feels that this would be worth doing for this particular sim, which will help us prioritize the modifications to HSlider.

**Comment by ycarpenterphet** [comment]
@jbphet I think this is worthwhile for this simulation, since the fonts are already so tiny for the tick labels (because of vertical space constraints), so any more space we can use (by allowing for alignment) before we have to shrink the font will substantially improve the usability of this sim on translation.

**Comment by jbphet** [comment]
Assigning to @phet-steele to verify, he should delegate if he doesn't currently have time.

**Comment by phet-steele** [comment]
@jbphet I took another pass, this sim is 👍
