### ISSUE TITLE
graph fails i18n test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#17]
I doubled the labels on the graph axes, to simulate translation to a different locale. Screenshot below of what it looks like. The placement of the labels is very obviously hardcoded for the English strings.

![screenshot_01](https://cloud.githubusercontent.com/assets/3046552/6406215/c7521b1e-bdea-11e4-8a13-9a073503c070.png)

**Comment by ycarpenterphet** [comment]
Horizontal axis label looks like it's fixed now, but the vertical label runs over the available length and behind the zoom buttons.

**Comment by ycarpenterphet** [comment]
The vertical graph axis label is much improved, but still is allowed to run behind the bottom zoom button.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
The graph axis labels look good when tested for i18n now. Thanks. Closing.
