### ISSUE TITLE
"look" problems with zoom buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#18]
Because the zoom buttons for the graph have a white background:
(1) they can't possibly highlight when the mouse is over them (there is no color brighter than white)
(2) they can't look 3D

Consider using a different background color. 

Compare with the same scenery-phet.ZoomButton used in ph-scale:

![screenshot_03](https://cloud.githubusercontent.com/assets/3046552/6406276/ae7baa6e-bdeb-11e4-8602-0e1ba66094fb.png)
![screenshot_02](https://cloud.githubusercontent.com/assets/3046552/6406277/affe7d9e-bdeb-11e4-905d-9b0c10dda0b2.png)

**Comment by ycarpenterphet** [comment]
The updated colors look fine - but we'll want to keep an eye out in interview to make sure that the yellow zoom button on the black background isn't overly tempting for students in their initial explorations. I think we'll be just fine, but I'll check when we do get to the interview phase.
