### ISSUE TITLE
Verify against design spec

### ISSUE THREAD

**Issue by jbphet** [phetsims/atomic-interactions#2]
ActualConcepts has delivered a version of this for testing, we need to compare its behavior to the specification.  This will be assigned to the lead designer.  Here is a link to the version that should be tested: http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.1/atomic-interactions_en.html.

**Comment by jbphet** [comment]
@ycarpenterphet - please create separate issues for anything that needs to be addressed, and I'll assign them as they come up.

**Comment by ycarpenterphet** [comment]
I think all issues related to the sim aligning with the spec in appearance or behaviour have now been reported as separate issues. Closing this parent task.
