### ISSUE TITLE
Oxygen Oxygen problem while in slow motion

### ISSUE THREAD

**Issue by phet-steele** [phetsims/atomic-interactions#20]
In 1.0.0-dev.2, while clicking and dragging the oxygen atoms into each other with slow motion enabled, they end up going crazy:

![atoinc](https://cloud.githubusercontent.com/assets/5863899/6449315/25341f30-c0dd-11e4-84ab-cbc36ab62a99.gif)

Seen on Win 8.1 browsers and iPad 2 (iOS 7)

Troubleshooting information:
Name: Atomic Interactions
URL: http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html
Version: 1.0.0-dev.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 9 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by ycarpenterphet** [comment]
Looks like this wacky behaviour shows up in the Java sim too, likewise only when looking at Oxygen-Oxygen in slow-motion.

**Comment by brroberts1231** [comment]
For phetsims/tasks#612 Seen on Win 7 browsers.
Still happens to a slightly lesser extent in dev.10. The pinned atom still jiggles somewhat violently, but now only on the horizontal. 
Also, after repeatedly dragging the moving atom into the pinned one, sometimes the pinned one would either move to a place where it's not supposed to be, or disappear entirely.

Screenshots: Recorder is unable to get a high enough framerate to really convey how fast the pinned atom is moving, but these still should show what happens well enough.

![atomic interactions1](https://cloud.githubusercontent.com/assets/11947677/15946640/f3a15fc8-2e54-11e6-91a9-3db0c34494a8.gif)
![atomic interactions2](https://cloud.githubusercontent.com/assets/11947677/15946641/f3a282cc-2e54-11e6-91a2-fd5a99386fed.gif)

**Comment by jbphet** [comment]
This should now be fixed, assigning to @phet-steele to verify.

**Comment by phet-steele** [comment]
@jbphet seems swell 😄
