### ISSUE TITLE
Atom color gradient should match Java sim (and design spec)

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#21]
The design spec and Java sim show atoms fading more quickly to black (or transparent), like so:
![screen shot 2015-03-02 at 1 43 43 pm](https://cloud.githubusercontent.com/assets/4682895/6450031/4e8d08ba-c0e2-11e4-9b57-3c64d9de9459.png) 
![screen shot 2015-03-02 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/4682895/6450102/c3140b2a-c0e2-11e4-971d-f9a9125869d2.png)

The current version of the sim does not look like it matches the either the gradient or color (this is most noticeable for Argon, but the colors are also slightly different for Neon etc.):
![screen shot 2015-03-02 at 1 43 53 pm](https://cloud.githubusercontent.com/assets/4682895/6450128/f3a29fb8-c0e2-11e4-9105-460e9a90d4f4.png)
![screen shot 2015-03-02 at 1 50 04 pm](https://cloud.githubusercontent.com/assets/4682895/6450183/4684dab6-c0e3-11e4-9a9b-f1b83e28ffab.png)

**Comment by ycarpenterphet** [comment]
Assigning to @jbphet to decide who should fix the color and opacity gradient.

Opacity/gradient: Not to spec.

Colors: It looks like the new colors match the "icon" colours used in atoms & molecules menu in https://github.com/phetsims/states-of-matter rather than the Java sim atom colors.The design spec does use the Java sim colors for the atoms, but we didn't explicitly say to do so, so I don't know if this should be up to us to change.

**Comment by ycarpenterphet** [comment]
Also, the original colors were color-blindness checked, while the new ones make it difficult to distinguish between Argon and Oxygen atoms (see also https://github.com/phetsims/states-of-matter/issues/49)

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar as well, since I know she's currently adjusting the colors in the legend in https://github.com/phetsims/states-of-matter/issues/49 and the legend should match these Java sim colors as appropriate too, since the Interactions screen in States of Matter will show both.

**Comment by jbphet** [comment]
I am going to leave this one assigned to me, since we are working to sort out the final colors and we can sit down together and tweak the gradient as needed once colors are finalized.

@ycarpenterphet - please note that using transparency in the gradients may have performance implications, so we'll need to test on slower devices and be ready to make tradeoffs between performance and optimal appearance when we get to this.

**Comment by ycarpenterphet** [comment]
When we optimize the transparency, we'll also need to keep in mind the visibility of the force arrows, which are overlaid on top of the atoms.

**Comment by jbphet** [comment]
I believe the color issues were addressed in https://github.com/phetsims/states-of-matter/issues/49, so the gradients are the next thing to finalize.  I've made some adjustments to make the edges of the particles reasonably "soft" yet still distinct, and to look decent in project mode too.  Assigning to @arouinfar to check on master.  If this looks good, please close the issue, if not, let's meet and do some tweaking.  I am making adjustments on the two screens available to me, your mileage may vary.

**Comment by arouinfar** [comment]
@jbphet the atoms look great on the black background, and projector mode has definitely improved. I don't think it needs further tweaking, so I'll go ahead and close this issue.
