### ISSUE TITLE
Color of total force arrow should match color in Forces menu

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#22]
In dev 2, the force arrows on the atoms look like this:
![screen shot 2015-03-02 at 2 31 03 pm](https://cloud.githubusercontent.com/assets/4682895/6451073/420710c0-c0e9-11e4-93b3-ced39cba5e88.png)

It should instead match the color of the Total force arrow shown in the Forces menu:
![screen shot 2015-03-02 at 2 30 59 pm](https://cloud.githubusercontent.com/assets/4682895/6451080/52e0eff6-c0e9-11e4-8d9c-0950ded1739c.png)

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar since this will also affect states-of-matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Verified. Closing.
