### ISSUE TITLE
Overlap between touch areas for Forces menu + Hide Forces radio button

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#23]
To conserve vertical space when we did the layout, we placed the Hide Forces option on the 'title' area of the Forces accordion box.

Unfortunately, the default behaviour of the accordion box is that touching anywhere in the 'title' bar opens/closes the accordion box. This seems to take priority, so it is basically impossible on a touch device to select 'Hide Forces'.

We either need to change the layout to add in title space (essentially using the layout in the Interactions screen of states of matter), or limit the open/close behaviour of the accordion box to only the touch area around the minimize "button".

@jbphet Can you comment on whether latter option is feasible, considering that the accordion box is a common component? If this is not currently an option, we might want to discuss if there are likely other sims that will need this functionality in future?

**Comment by pixelzoom** [comment]
@ycarpenterphet wrote:

> Unfortunately, the default behaviour of the accordion box is that touching anywhere in the 'title' bar opens/closes the accordion box. 

This sounds like a bug in AccordionBox. When options.showTitleWhenExpanded === false, there should be no title bar when the box is expanded, and the box should be collapsable only via the collapse button.

**Comment by pixelzoom** [comment]
Btw...  For the record, I really dislike the showTitleWhenExpanded feature of AccordionBox. Don't like the way it looks, behaves, or how it complicates the implementation with weird special cases.

**Comment by pixelzoom** [comment]
AccordionBox is fixed. Clicking in the title area does nothing when showTitleWhenExpanded:false.

**Comment by ycarpenterphet** [comment]
@jbphet If you can publish a new dev version, I can verify if the accordion box fix solves this problem

**Comment by jbphet** [comment]
New version published, see http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.3/atomic-interactions_en.html.  Seems to me like the issue is fixed, but I'll assign to @ycarpenterphet for final verification.

**Comment by ycarpenterphet** [comment]
Looks good. closing.
