### ISSUE TITLE
Improve look of projector mode

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#25]
Projector mode looks exactly as we specified in the design doc, but some polishing could be done to significantly improve the look.

(1) Have the gradient of the moveable atoms fade out to transparent instead of to black (this might actually be best generalized to the original atoms on black background, so that fewer changes need to be made or redrawn when we switch between modes).

(2) Add black stroke border to the control menus at the right side.

(3) possibly change the color of the zoom controls [but this might eventually be fixed in https://github.com/phetsims/atomic-interactions/issues/18]

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar on this as well - the design elements differ a bit between this and the interactions screen, but at least the change to the gradients on the large atoms will also affect States of Matter

**Comment by ycarpenterphet** [comment]
Looks like the only outstanding issue here is the gradient on the atoms

> (1) Have the gradient of the moveable atoms fade out to transparent instead of to black (this might actually be best generalized to the original atoms on black background, so that fewer changes need to be made or redrawn when we switch between modes).

**Comment by jbphet** [comment]
This issue has been sitting around for a while, and @arouinfar recently created an issue for projector mode colors in States of Matter, see https://github.com/phetsims/states-of-matter/issues/135.  Assigning to @arouinfar to determine whether there is anything additional that needs to be done for Atomic Interactions or if the SOM issue and what has been done so far covers it.

**Comment by arouinfar** [comment]
Aside from the gradient on the atoms that YY pointed out, I think the only other thing we'd need to change is the color of the potential curve. Yellow on white is unlikely to project well, so let's keep the red color used in the regular mode.

@jbphet how are the atoms generated? Is it artwork, or something done in code?

**Comment by jbphet** [comment]
@arouinfar and I reviewed this together, made some final changes, and agree that it is now acceptable.  Closing.
