### ISSUE TITLE
Fix alignment of pause/play button

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#26]
Increase spacing between Slow Motion/Normal radio buttons and the "Play" button to better match the design document:
![playpause-16](https://cloud.githubusercontent.com/assets/4682895/6452541/a0a79e38-c0f3-11e4-8c46-59842df07985.png)

This should also fix the overlapping touch areas between these controls. 

Also, adjust spacing between Play and "step forward" buttons to minimize or eliminate overlap between the touch areas.

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar as well since I know this will affect the interactions screen in states of matter.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @ycarpenterphet  for verifcation

**Comment by ycarpenterphet** [comment]
Overlap issue is fixed. Closing.
