### ISSUE TITLE
Position of pin needs to be adjusted to match spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#28]
The Pin graphic should be positioned higher and to the left in the starting atom, as shown in the design doc:
![screen shot 2015-03-02 at 4 33 08 pm](https://cloud.githubusercontent.com/assets/4682895/6453329/16328716-c0fa-11e4-90cc-145060a33d04.png)

Compare: In dev2, the pin is positioned lower and further to the right:
![screen shot 2015-03-02 at 4 33 39 pm](https://cloud.githubusercontent.com/assets/4682895/6453365/65daf3f2-c0fa-11e4-9180-a655bf302c8e.png)

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar as well, since I know this will affect States of Matter.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in latest code. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
