### ISSUE TITLE
Mouseover behaviour of "hand" should match behaviour of moveable atom

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#29]
When you mouseover the moveable atom, the mouse cursor changes to "hand" icon. For consistency, this should also happen when you mouseover the hand graphic that appears on the moveable atom at the start of the game.

**Comment by ycarpenterphet** [comment]
Assigned to @jbphet to decide who should take this on, AND whether we should hold off until we finalize the hand graphic (e.g. we'll still need to see it in interview to know if it works, or whether we have to use a different graphic, or go back to the 'Move the atom' text)

**Comment by jbphet** [comment]
I'd rather not hold off on this because the behavior strikes me as incorrect too, and it doesn't match the prompt in the Java sim.  The hand should disappear when the atom is initially dragged.  Assigning to ActualConcepts.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for verification.

**Comment by ycarpenterphet** [comment]
Ah, actually, you brought up an interesting point @jbphet. In the Java sim, the "prompt" wasn't an interactive element that you could click and drag. So the prompt disappears when you 'grab' the atom, rather than when you release.

In the current sim, the hand currently is interactive - you can grab either anywhere on the atom or the hand in order to move the atom (which is why I asked that the mouseover be changed to match the behaviour - and this has been fixed as of dev4).

If the hand is an interactive, it doesn't make sense (to me) for it to disappear until you release it (otherwise, you could end up having "grabbed" the empty space next to the atom). With it placed where it is (on top of, rather than pointing at the atom from the side), I also think being able to grab by clicking on the hand is important.

So, I think that although the behaviour here doesn't match the Java sim, I think it makes sense for the behaviour to remain as-is (unless we see issues in interview!)

cc @arouinfar (just to keep her in the loop for States of Matter)

**Comment by jbphet** [comment]
The mouseover behavior is verified in the current master branch, and since @ycarpenterphet feels like the other aspects of the behavior are correct, all concerns mentioned in this issue have been addressed.  Closing.
