### ISSUE TITLE
Alignment of horizontal axis label does not match design spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#3]
The text "Distance between atoms" should be aligned in the center of the horizontal axis and there should be slightly more vertical space between the axis and the text.

See for example this image from page 4 of the design document: 
![startup appearance](https://cloud.githubusercontent.com/assets/4682895/6381305/69f7f652-bcfd-11e4-8ead-e98bbc4462d6.png)

Vs. the current dev version of the simulation:
![screen shot 2015-02-25 at 2 50 57 pm](https://cloud.githubusercontent.com/assets/4682895/6381356/c7292846-bcfd-11e4-8884-91c42025caf5.png)

**Comment by ycarpenterphet** [comment]
This issue also applies to the Interactions screen of States of Matter. @jbphet & @arouinfar - I've created a duplicate issue there that references this.

**Comment by jbphet** [comment]
Sounds like this may be fixed, assigning to @ycarpenterphet to verify on Looks like this may have been fixed. Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html. If fixed, please close, if not, please assign to @kmsravindra.

**Comment by ycarpenterphet** [comment]
Is it possible for the label to be center-aligned relative to the graph axis? This would give the best match for the design.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks good, even when tested for i18n compatibility. Closing.
