### ISSUE TITLE
Custom attraction should not reset to initial settings (unless Reset-All used)

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#30]
Currently, the Custom attraction settings (i.e. diameter and strength) reset to their initial settings when switching to another pair of atoms and then back to Custom. Note: This was unfortunately the behavior of the Java sim as well. 

It makes more sense if settings and the position of the sliders would remain unchanged unless the student changes them deliberately or hits reset-all, so that a student or instructor can draw comparisons more readily. 

Behaviour should be more similar to the weaker-stronger slider in Acid-Base Solutions, which retains its position even when the toggle switch turns off/removes the slider.

**Comment by ycarpenterphet** [comment]
Tagging @arouinfar as well since this will affect States of Matter too.

**Comment by phet-steele** [comment]
@aadish This is working for the case of the Interaction screen, but not in the Phase Changes screen in SOM. Making a new issue in the appropriate repo and closing this one.
