### ISSUE TITLE
Revise pushpin graphic

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#32]
The pushpin looks more like it's floating on top of the atoms than pinning them, because the whole pin is visible (which looks great in the menu, but not great in context).

@arouinfar and I should probably discuss.

**Comment by arouinfar** [comment]
@jbphet I think I can make the tweaks to the artwork myself. I'll go ahead and give it a try.

**Comment by arouinfar** [comment]
Perhaps if we adjusted the perspective a bit we'd avoid the float-y look. 

Adjusted (left) vs. Original (right)
![image](https://cloud.githubusercontent.com/assets/8419308/17382054/4d85087a-598c-11e6-8252-4ecb751eb31e.png)

I'll email @jbphet the updated push pin asset for implementation.

**Comment by jbphet** [comment]
The new artwork is integrated and I reviewed it in situ with @arouinfar and she gave it the thumbs up.  Closing.
