### ISSUE TITLE
Horizontal adjustment arrow doesn't always stay with graph

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#34]
This is an existing issue in the Java sim, and has been carried through to the HTML5.

In the Custom Attraction mode, if the interaction strength is adjusted to be very small, the horizontal adjustment arrow is now floating and not attached to the curve:
![screen shot 2015-03-03 at 4 08 09 pm](https://cloud.githubusercontent.com/assets/4682895/6474643/c61c89ea-c1bf-11e4-81ad-cfdc761b6895.png)

This isn't ideal behaviour (it's best if the control stayed attached to the thing it controls), but is relatively low priority to fix. 

Note that we're also likely moving the horizontal arrow control higher on the curve (see #24), so that may affect the position too.

**Comment by ycarpenterphet** [comment]
Clarification - the position of the horizontal adjustment arrow is set by the value of sigma, since that's literally what it adjusts. We'll have to make a decision as to whether the horizontal arrow control should be longer, so that it stays with the curve too, especially if we move it higher up vertically to solve #24.

I'll try out a couple of options once we solve #24 to see which works best, before we make a decision on this one. For now, let's do nothing about this issue.

Tagging @arouinfar since this will affect States of Matter too.

**Comment by ycarpenterphet** [comment]
Flagging this as something for @arouinfar to watch for in interviews - if there are no issues in interview with the interface as is, we can close this issue.

**Comment by ycarpenterphet** [comment]
This is much improved now that the adjustment arrows are larger. Likely won't be an issue.

**Comment by arouinfar** [comment]
It looks like this issue has already been resolved. The horizontal adjustment arrow stays tied to the curve, and has a generous touch area. 

![image](https://cloud.githubusercontent.com/assets/8419308/17375686/5336430a-596f-11e6-959b-c398cf84b2ca.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/17375676/45050672-596f-11e6-96f1-743079b8f04f.png)

I'm going to go ahead and close this issue. If something arises in interviews, we can revisit.
