### ISSUE TITLE
Speed of moving atom significantly slower vs. Java sim

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#35]
There is an issue causing the atom to move slower than it should in the HTML5 sim (dev 3), even during "Normal" speed motion.

Details:
I originally thought this was due to the changed graph dimensions, but I compared the two sims by moving the Neon atom so that the two Neon atoms are just touching, and timed how long it took to return to this position once released.

The HTML5 sim takes roughly twice as much time to return to the same position.

@jbphet suggested I run the sim w/ the profiler parameter, and that seems to show 58-60 fps throughout the motion of the atom, so I don't think it's a performance issue.

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar just to keep her in the loop, since this will also affect States of Matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
It now appears that the atom is moving 2x faster than the Java sim.

@ChandrashekarBemagoni, can you investigate the cause and see if we can more closely match the movement speed observed in the Java sim?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
This now looks comparable. Thanks, closing!
