### ISSUE TITLE
Arrows frozen in size when paused

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#36]
Current sim behaviour does not match the Java sim.

When the sim is paused, and the atom is moved the Force arrows should still change in proportion to the relative positions of the atoms.

For example, if I display the total force arrow, and then pause the sim, I see this:
![screen shot 2015-03-03 at 5 20 16 pm](https://cloud.githubusercontent.com/assets/4682895/6475614/9a11d22e-c1c9-11e4-9e0f-214c216f4c19.png)

With the sim still paused, if I move the atoms to a different position, the force arrows <i>should</i> change in response, but instead, I see this, which incorrectly represents the forces on the atoms as unchanged:
![screen shot 2015-03-03 at 5 21 15 pm](https://cloud.githubusercontent.com/assets/4682895/6475623/c1d34590-c1c9-11e4-867a-7a834e2cb26e.png)

Only if I press Play or Step-Forward do the correct force arrows appear, like so (very small, and pointing towards each other):
![screen shot 2015-03-03 at 5 22 24 pm](https://cloud.githubusercontent.com/assets/4682895/6475638/e24bca90-c1c9-11e4-9d1e-c9c81149916b.png)

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar just to keep her in the loop, since this will also affect States of Matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/atomic-interactions/commit/e68f6562fb8c9fec18a3585522c064158b150ab9. Assigning to @ycarpenterphet for verification.

**Comment by ycarpenterphet** [comment]
Looks fixed. Closing.
