### ISSUE TITLE
Force arrows on atoms should be partially transparent to match Java sim

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#37]
Current force arrows on the atoms are 100% opaque, which makes it difficult to see all of the information being displayed when they overlap:
![screen shot 2015-03-03 at 5 30 23 pm](https://cloud.githubusercontent.com/assets/4682895/6475751/00a63e2a-c1cb-11e4-8cd7-89bc3d537b42.png)

The updated colors look good, but please increase the transparency to mimic the Java sim implementation:
![screen shot 2015-03-03 at 5 30 48 pm](https://cloud.githubusercontent.com/assets/4682895/6475763/24609310-c1cb-11e4-8f1c-fec70b9374fb.png)

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar just to keep her in the loop, since this will also affect States of Matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification.

**Comment by ycarpenterphet** [comment]
Looks good, thanks! Closing.
