### ISSUE TITLE
Hand graphic on moveable atom should remain visible until an atom is moved

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#38]
Just like the "Move the atom" text/arrow in the Java sim, the hand graphic in the new sim should only disappear after an atom is moved (either by the user directly moving it, or by the user moving the dot on the graph):
![screen shot 2015-03-03 at 5 37 33 pm](https://cloud.githubusercontent.com/assets/4682895/6475824/06d350de-c1cc-11e4-8906-a5f067b61336.png)

If the user switches which atoms are in use before moving an atom (i.e. clicks on the radio buttons in the atoms list at the right), this should have no effect on whether the hand is visible.

**Comment by ycarpenterphet** [comment]
(tagging @arouinfar just to keep her in the loop, since this will also affect States of Matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification.

**Comment by ycarpenterphet** [comment]
Issue with the hand disappearing when atoms are changed is fixed, thanks.

However, the hand <i>should</i> disappear when the atom is moved in any way, to match the Java simulation, as stated above:

> (either by the user directly moving it, or by the user moving the dot on the graph)

This still needs to be resolved - assigning back to @ChandrashekarBemagoni.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet  for verification.

**Comment by ycarpenterphet** [comment]
Looks good, thanks. Closing.
