### ISSUE TITLE
Adjustment controls on graph need to match design spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#39]
Compare the mock-up:
![screen shot 2015-03-03 at 5 55 00 pm](https://cloud.githubusercontent.com/assets/4682895/6476057/862a261c-c1ce-11e4-91e5-398311bad30d.png)

To the current HTML5 version:
![screen shot 2015-03-03 at 5 57 07 pm](https://cloud.githubusercontent.com/assets/4682895/6476086/d9317f18-c1ce-11e4-813c-87ce5692f5d6.png)

Note in particular that the horizontal green line should be thinner, the vertical arrow control should be vertically-centered on that line, and the green color of all of these adjustment controls should be more green (i.e. less yellow).

If possible, the arrow heads on both controls should also be a bit wider, but this not critical.

(tagging @arouinfar just to keep her in the loop, since this will also affect States of Matter)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks great. Closing.
