### ISSUE TITLE
Sliders for Custom Attraction: size + alignment don't match design spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#4]
The design document shows the the Custom attraction sliders like so:
![screen shot 2015-02-25 at 2 54 47 pm](https://cloud.githubusercontent.com/assets/4682895/6381422/4e2291b6-bcfe-11e4-9171-4395ff9f23e7.png)

The sliders in the current version look like this instead:
![screen shot 2015-02-25 at 2 53 28 pm](https://cloud.githubusercontent.com/assets/4682895/6381511/db2694fe-bcfe-11e4-8653-80e057a62da3.png)

Please...
(1) Increase the slider width to match the design doc, and align the heading of each slider (e.g. Atom Diameter) to the left-edge of the radio button (and adjust the slider left-edge and labels appropriately). 

(2) Remove the labels "small" and "large" from the Atom diameter slider, as shown in the design doc, and decrease vertical spacing in response to this.

**Comment by ycarpenterphet** [comment]
This is improved in dev2, but still does not match the spec - sliders are taller than shown in the mockup, and both vertical and horizontal spacing need adjustment

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
