### ISSUE TITLE
sim has no strings file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/atomic-interactions#40]
Broken by phetsims/atomic-interactions#15.

atomic-interactions has no strings file and it's title is defined in states-of-matter. This causes the build tasks that generate README.md to fail. (And unclear how Rosetta will behave for a sim with no strings file.)

**Comment by pixelzoom** [comment]
Fixed, assigning to @jbphet to review.

**Comment by jbphet** [comment]
I was using the Concentration sim as a model, and it didn't have a strings file as of yesterday.  I see that it now has one, and that all sims require one for the generation of the README.md file to work.  So, this fix seems fine to me.  Closing.
