### ISSUE TITLE
Remove white border around option panels

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#42]
The panels on the right-side of the screen (where you select the atoms or forces) both currently have a white stroke border around them which was not present in the mockup.

Can this be removed?

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks good, thanks. Closing.
