### ISSUE TITLE
Pushpin changes position when custom attraction is the first option selected

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#43]
If the sim is loaded and then the Custom Attraction option is selected, the pushpin graphic changes position - which should not happen.
![screenshot 2015-04-16 10 30 34](https://cloud.githubusercontent.com/assets/4682895/7185984/bb9eb8a4-e423-11e4-9c75-59a36df180c0.png)

This does not happen if another atom combination is selected first (e.g. select Neon-Argon before selecting Custom Attraction), and the pushpin goes back to the correct position if another atom pair is selected and then we return to Custom.

This is how it should look:
![screenshot 2015-04-16 10 30 40](https://cloud.githubusercontent.com/assets/4682895/7186009/f4496a1e-e423-11e4-8bfc-b1e4cba8f33a.png)

**Comment by ycarpenterphet** [comment]
It looks like this is probably connected to how #28 was fixed.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit.Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks fixed, thanks. Closing.
