### ISSUE TITLE
Alignment of radio buttons

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#44]
According to the design document, the radio buttons in the top menu should be aligned horizontally with the radio buttons in the Forces menu:

Design:
![image](https://cloud.githubusercontent.com/assets/4682895/7187674/74b77924-e42f-11e4-88c3-3588b427dfce.png)

Currently, they are too far to the left. Please shift the top radio buttons to the right to fix this alignment issue.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit .Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks fine, thanks. Closing.
