### ISSUE TITLE
Rounded corners on top and bottom menus are different

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#45]
Is it possible to ensure that the rounding of the corners in the top (atoms) and bottom (forces) menus are the same, and match the design specifications more closely:

Specifications from design doc: 
![image](https://cloud.githubusercontent.com/assets/4682895/7187717/e3ae492a-e42f-11e4-893b-7c54a8bd0f23.png)

Current sim corners:
![screenshot 2015-04-16 11 58 48](https://cloud.githubusercontent.com/assets/4682895/7187734/fdd88ae0-e42f-11e4-9d67-b0221900203f.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit .Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
