### ISSUE TITLE
Increase vertical spacing of text in top menu + menu height

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#46]
Please increase the vertical spacing between text labels to more closely match the original specification:
![screenshot 2015-04-16 12 02 46](https://cloud.githubusercontent.com/assets/4682895/7187802/825d1b46-e430-11e4-8dbe-e3b289bcee3d.png)

Notice, for example, that the Atom Diameter label is currently vertically too close to the Custom Attraction radio button, and should have more buffer space between them:
![screenshot 2015-04-16 12 04 34](https://cloud.githubusercontent.com/assets/4682895/7187841/c4845b88-e430-11e4-9f7b-651e5009e413.png)

ALSO, this will be easier if the total height of the top menu is increased, again to match the specifications. Notice that when both menus are fully open (as shown above), the bottom menu extends nearly to the bottom of the screen in the design mockup. In the current sim, the top menu is smaller than the spec.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit .Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks much improved. Closing.
