### ISSUE TITLE
The dragged graph particle can become detached from mouse

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/atomic-interactions#48]
Steps to reproduce:
1. Drag the particle on the graph
2. Move it far to the left (the particle will be stuck at some point)
3. Move it to the right again. The particle will be far to the left of the mouse

![atomic-interactions-bug](https://cloud.githubusercontent.com/assets/480878/9375002/025f8db6-46b9-11e5-8a60-393c66b726a0.PNG)

**Comment by phet-steele** [comment]
@aadish mouse is staying attached on Mac OSX 10.11.5 Chrome.
