### ISSUE TITLE
Width of top (atoms) options menu does not match spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#5]
The top menu is narrower than the Forces menu in the current version:
![screen shot 2015-02-25 at 3 31 46 pm](https://cloud.githubusercontent.com/assets/4682895/6383456/e6d34c7a-bd0d-11e4-95eb-689722bccb25.png)

Please adjust the width of the top menu to match the spec by expanding the purple area (note alignment of both left and right edges), but do not move the radio buttons:
![screen shot 2015-02-25 at 4 47 12 pm](https://cloud.githubusercontent.com/assets/4682895/6383472/15d1bb7e-bd0e-11e4-91b6-15b78e341ddc.png)

**Comment by pixelzoom** [comment]
Looks like a candidate for using the new minWidth option that was added to sun.Panel.   For example:

``` js
var maxContentWidth = Math.max( topContent.width, bottomContent.width );
var topPanel = new Panel( topContent, { minWidth: maxContentWidth } );
var bottomPanel = new Panel( bottomContent, { minWidth: maxContentWidth } );
```

**Comment by ycarpenterphet** [comment]
Looks like the two panels now have the same width, but that the radio buttons in the top panel are now too close to the left edge compared to the design spec.

**Comment by ycarpenterphet** [comment]
Also, comparing the sim directly to the mockup, it appears that both panels are actually slightly narrower, and shifted to the right. 

This is especially noticeable if the mockup is overlaid on top of the current version (mockup on bottom, current sim on top):
![screen shot 2015-03-05 at 1 02 25 pm](https://cloud.githubusercontent.com/assets/4682895/6513401/02d6b7ec-c338-11e4-85fa-bbd4a4b502b0.png)

**Comment by ycarpenterphet** [comment]
As of dev6, it looks like the width of the top panel is a good match for the design specifications, and the alignment issue has been corrected.

However, the top panel is again slightly narrower than the bottom panel.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit .Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Widths are now the same, thanks. Opening a new issue for other menu changes needed to match spec.
