### ISSUE TITLE
improve the hand artwork

### ISSUE THREAD

**Issue by jbphet** [phetsims/atomic-interactions#53]
The hand that cues users to grab the movable atom looks a bit odd, and could be improved.  @ariel-phet and I discussed this, and he requested that I create an issue and assign it to him, so here it is.

Here is a screenshot that shows what the hand currently looks like:
![atomic-interaction-hand](https://cloud.githubusercontent.com/assets/3082831/17185846/f922e974-53ef-11e6-937d-829f39e5f60b.PNG)

**Comment by ariel-phet** [comment]
I think we want something a bit more like this 

![141-512](https://cloud.githubusercontent.com/assets/4051174/17193749/ae23cf48-5411-11e6-8191-fca677fa55f2.png)

**Comment by ariel-phet** [comment]
And perhaps we should use a dark-ish gray stroke, so that it will have contrast on the black background and the atom.

**Comment by arouinfar** [comment]
How about something like this @ariel-phet @jbphet?
![image](https://cloud.githubusercontent.com/assets/8419308/17451293/eb62bfaa-5b22-11e6-9181-622ec24c6322.png)

**Comment by ariel-phet** [comment]
Yes, that looks much better to me!

**Comment by arouinfar** [comment]
I've sent the artwork to @jbphet to implement.

**Comment by jbphet** [comment]
New artwork is integrated, closing.
