### ISSUE TITLE
Cannot drag oxygen-oxygen tracking dot along curve

### ISSUE THREAD

**Issue by arouinfar** [phetsims/atomic-interactions#55]
In dev.11 I am unable to drag the oxygen-oxygen tracking dot along the potential curve.

For other pairs (like argon-argon), I can drag the dot along the curve. However, I cannot do the same for oxygen-oxygen, though I can move the unpinned atom.
![trackingdot](https://cloud.githubusercontent.com/assets/8419308/17632473/aeff3954-6085-11e6-9719-d768ca5f8739.gif)

By the way, I had the sim paused while making this video to make the interactions a bit clearer. When unpaused, I have the same difficulties.

**Comment by jbphet** [comment]
This was due to a hard-coded value in the drag handler for the marker on the diagram.  I changed the code to set a minimum allowable value from the view, and this seems to have resolved the problem.  Should be fixed now, assigning to @arouinfar to verify on master.

**Comment by arouinfar** [comment]
Looks good @jbphet. Thanks!
