### ISSUE TITLE
Size and alignment of "Pinned" and "Moving" labels does not match spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#6]
The design document shows the following, where the heading fonts are significantly smaller than the radio button label font:
![screen shot 2015-02-25 at 4 53 08 pm](https://cloud.githubusercontent.com/assets/4682895/6383558/e04d260e-bd0e-11e4-9f0d-bbbe367bc0df.png)

Please...
(1) Adjust the size and position of the pin graphic to match the design
(2) Reduce the font size for the 'Pinned' and 'Moving' labels to match the design
(3) Adjust the alignment of these labels (so that they are left aligned with the column below, as shown in the design document).
(4) If possible, more closely match the spacing between columns shown in the design.

**Comment by pixelzoom** [comment]
Clearly not fixed in a general way that supports i18n.  Here's what it looks like when 'XXX' is added to the 'Pinned' and 'Moving' labels:

![screenshot_225](https://cloud.githubusercontent.com/assets/3046552/6406177/4838fa64-bdea-11e4-905c-6d1d19fd59ef.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits.Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
The size and alignment don't quite match the mockup yet:

Design document:
![screen shot 2015-03-05 at 1 07 23 pm](https://cloud.githubusercontent.com/assets/4682895/6513548/fd6fbe24-c338-11e4-9e2a-ad72be426461.png)

Current sim:
![screen shot 2015-03-05 at 1 10 52 pm](https://cloud.githubusercontent.com/assets/4682895/6513576/23bb30fe-c339-11e4-80b9-0379a4a80080.png)

Note especially the spacing between the top of the menu and the pinned/moving text, and the size of the pin.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits . Assigning to @ycarpenterphet  for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
