### ISSUE TITLE
[Multitouch] Fixed interactions will have the appearance of a changing atom diameter

### ISSUE THREAD

**Issue by phet-steele** [phetsims/atomic-interactions#60]
1. Finger A, manipulate the Atom Diameter slider.
2. Finger B, switch to another interaction option.
3. Slide finger A around.

@jbphet, the color fills representing a changing atom diameter will be seen. No, this does not actually change the diameter of the non-custom atoms.

![ai02](https://cloud.githubusercontent.com/assets/5863899/18522879/21c58b20-7a6f-11e6-9ae4-e94a4841eccc.gif)

Assigning to @ariel-phet to decide if this should be fixed now or later. Seen on iPad Air 2 iOS 9.3.5, for phetsims/tasks/issues/693.

**Comment by ariel-phet** [comment]
Hmm, this does seem like something one could do on accident, (dragging the atom diameter and hitting one of the other options on the screen), and then the sim will be in quite an odd state.

@jbphet could you investigate and see if there is an easy solution?

**Comment by jbphet** [comment]
The sim is only in an odd state very temporarily, but I went ahead and added code that prevents this problem anyway.  Gradients are now re-enabled on a change of particle type and the fill change is only made for adjustable particles.  See the commit for details.  To make sure I have fully understood and resolved the issue, I'll have @phet-steele test before publication.

**Comment by jbphet** [comment]
I had @phet-steele test on my machine, and he said that it appeared fixed, but he'd still like to test on the next RC, so I'll leave this open and assigned to him.

**Comment by phet-steele** [comment]
It looks great, closing.
