### ISSUE TITLE
[Multitouch] Atom movement while still dragging

### ISSUE THREAD

**Issue by phet-steele** [phetsims/atomic-interactions#61]
1. Finger A, manipulate either Custom Attraction slider.
2. Finger B, manipulate the atom.
3. Release finger A.
4. Drag finger B to the left of the screen.

@jbphet, the sim seems to interpret step 3 as releasing the atom, not just the slider. The atom begins to move, but can simultaneously be controlled by finger B.

![ai01](https://cloud.githubusercontent.com/assets/5863899/18522874/1c6d3a88-7a6f-11e6-8952-379744a96f4a.gif)

Assigning to @ariel-phet to decide if this should be fixed now or later. Seen on iPad Air 2 iOS 9.3.5, for phetsims/tasks/issues/693.

**Comment by ariel-phet** [comment]
I think this is a "won't fix" issue. It is a rare of enough use case, and I don't think the user will be surprised that by trying two change to things at once the system is fighting itself.

Good find though @phet-steele! 

Marking won't fix and closing
