### ISSUE TITLE
Remove the color fill on diameter change

### ISSUE THREAD

**Issue by phet-steele** [phetsims/atomic-interactions#64]
@ariel-phet @jbphet @arouinfar We can probably do away with the color fill that occurs when changing atom diameter. Its purpose was to improve performance while changing the diameter and prevent weird appearance bugs. As the below mulitouch "bug" reveals, the sim handles the gradient re-drawing quite well. iPad 2 still has remarkable performance when rapidly changing the atom's size. I also checked Win 10 Chrome & Edge and saw no graphical problems. After all, I think this color fill is a relic of the Java code....

![ai03](https://cloud.githubusercontent.com/assets/5863899/18765271/34d30e9a-80d2-11e6-9e73-e290b96c78ae.gif)

**Comment by phet-steele** [comment]
@ariel-phet liked the idea.

**Comment by arouinfar** [comment]
Sounds good @phet-steele! If there aren't any performance concerns, I don't see any reason to keep the color change feature.

**Comment by jbphet** [comment]
Indeed, this was a performance or behavior issue in the Java sim and may no longer be necessary.  We should test it thoroughly on all platforms before going live with it, so I'll make the change and roll it into an RC for testing.

**Comment by phet-steele** [comment]
This looks great. Everything is performing well. See the tested platforms in the referenced tasks issue.
