### ISSUE TITLE
User comments: O-O formation issues

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/atomic-interactions#65]
Comment from Sandor Sep 27, 2016:

> I have just translated the HTML5 version of the old Java sim. (The old strings have not been included int he form.)
> Please pass the attached screenshot to the (theoretical/computational) chemist expert who takes care of your sims for reconsideration.
> The O-O example obviously shows molecule formation. It is very strange to me to describe it in terms of van der Waals force.
> On the other hand I like this example, but I think it is misleading in this form.

**Comment by oliver-phet** [comment]
Perhaps @arouinfar can comment?

**Comment by ariel-phet** [comment]
Not sure, but I think @amyh-phet will have more insight

**Comment by arouinfar** [comment]
@oliver-phet @ariel-phet @amyh-phet 

One of the learning goals of the simulation is to

> Contrast the potential well and behavior of a bonded pair of atoms with unbonded pairs.

This behavior was present in the Java sim, though sigma and epsilon were adjusted to be more realistic for the O-O pair. YYC stated in the design doc that:

> If using LJ potential to approximate the O-O bonding interaction, epsilon should roughly correspond to the average bond energy (since that’s the well-depth), and sigma can be calculated based on the average bond length, since the bottom of the well should be located at the equilibrium bond distance. Consulted with Robert Parson who agrees that this sounds right that the dissociation energy can be used for epsilon.

This has also been noted in the Teacher Tips.

As far as I know, the Lennard-Jones potential is used to describe the interaction of two neutral atoms whether they are bonded or not. The two terms of the L-J Potential correspond to the van der Waals attraction and the Pauli repulsion (which we label as "electron overlap"), so I'm not sure I understand Sandor's comment...

**Comment by amyh-phet** [comment]
@arouinfar and @oliver-phet     The Lennard-Jones potential is typically used to calculate attractions between two neutral particles and models intermolecular attractions, not covalent bonds.  I think Sandor has a point that it is a bit unconventional to use L-J potentials for bonded atoms.  We did attempt to address this in the Teacher Tips, but perhaps I need to reword how the O-O values for sigma and epsilon were calculated.  From YYC's notes, the equation for the L-J potential was not used for this calculation, but information about bond energy/length was used to create the graph for oxygen.

Just curious, do we know if Sandor looked at the Teacher Tips?

**Comment by amyh-phet** [comment]
@arouinfar and @oliver-phet   Can this issue be closed?

**Comment by ariel-phet** [comment]
There was a further concern raised in #68 

I had some email discussion with the user, and I think I understand the concern better. Basically, when you displace the moveable atom from the potential well minimum in the O-O scenario, it causes the "pinned" atom to vibrate on "collision", this vibration then goes away, and the oscillation does not go as high on the walls of the potential well, implying a loss of kinetic energy.

It seems there are issues with showing O-O here, for multiple reasons. I need to discuss this KE loss more with @jbphet

**Comment by ariel-phet** [comment]
I am also going to probe Emily Borda regarding these questions, she might have some thoughts/insight.

**Comment by ariel-phet** [comment]
Emily Borda is on vacation but said she would give some input the week of 7/10

**Comment by ariel-phet** [comment]
Further comments by the user who raised concerns in #68 

> Having read through the thread in the hub,  I ought to join the negative sentiment as to presenting the O+O dynamics on par with the noble pairs. To some extent the dynamics of the oxygen is not different,  but the ensuing discussion may be out of scope. However,  just one last response:  if a bond is formed and KE release, it cannot go to translation of the molecule,  because it is released in the center of mass frame of reference. In short,  when 2 Oxygen atoms collide, it is impossible for a molecule to form. If the initial state is already a bond state (I.e. molecule) then we are in a vibrational state, which has to be periodic (unless one takes into account IR photon emission, or collisions with other particles.)
> 
> This is a good point to thank you and all of the team for providing us, STEM teachers, with good sims. Furthermore, PHET is becoming a standard for good sims, and that means you have added responsibility.

**Comment by ariel-phet** [comment]
Emily Borda responded:

> 
> The problem seems to be that the O-O part of the sim is able to go from an unbonded to bonded situation without the intervention of a third particle to take away excess energy, which seems to violate the law of conservation of energy.  If PE decreases, KE must increase.  This appears to be what happens, but KE should be so large that the O atom is able to escape its bonding partner after a collision.  In order for it to become trapped in a bond, it needs to lose energy.  This is one of the major goals of my Energy & Bonding sim; to model interactions where a third particle either inputs energy (in the case of bond breaking) or takes energy away (in the case of bond formation).  
> 
> I see the Atomic Interactions sim as modeling what a bond is, once it is formed.  It does a good job of showing the PE/KE tradeoffs and forces involved in the oscillation of two atoms involved in a bond.  But without a third particle it can't model bond breaking or formation.  To me, what this means for the Oxygen tab is that if I drag the unpinned O to the right, and it moves to the left, toward the pinned O, it should come back to the exact place I dragged it in the first place.
> 
> I hope this makes sense; I'd be happy to have a phone or zoom meeting to chat about this.

It seems we should revisit this behavior

**Comment by kathy-phet** [comment]
I am leaning towards keeping the O-O example, but making it behave like the other examples (that is not bond automatically). I sent an email off to Joe Redish, to get his feedback on this proposed change: 

>  
> Hi Joe,
> 
> I'm writing because we are considering various options to address the issues you (and others) have raised around the depiction of the O-O bonding in the Atomic Interactions sim.
> 
> I was hoping to get your thoughts on the following proposal:
> 
> - Keeping the O-O example within the sim, but removing the bonding behavior such that it behaved like all the other interactions shown. So, depending on the release position, it will keep oscillating with the same energy, or it would fly away and not bond. In this way, the example can still address some of the original learning goals of showing the potential well for O-O is much deeper than for the other pairs and that the forces are much stronger. But now it will (perhaps) spur on discussion around why it doesn't bond in this example, and what would need to happen to make it form a bond (e.g. something to carry off the extra energy). And to model a bonded O-O and to discuss that it would need a lot of energy to break the bond, you can position the O originally near the bottom of the well.
> 
> Would this address your concerns?
> 
> Thoughts?
> 
> Thanks!
> Kathy

I will update this issue when I hear back from Joe.

**Comment by kathy-phet** [comment]
I discussed the above proposal with @arouinfar, before emailing Joe, and she thought it seemed OK. It seemed to allow addressing the original learning goals around O-O still - just in a different way. I also sent a note to Carl just now regarding this proposal. Will update as I hear back.

@ariel-phet - Would this solution work from your knowledge of the discussions?

**Comment by kathy-phet** [comment]
From Carl: 

> I do agree with you that it is important to keep the o-o example as a contrast. 
> 
> Your solution seems good to me.  I cannot come up with anything better.  
> 
> It would be nice to have some way to turn on or off a way to carry away the energy to show what the actual ground bound state looks like and need for three body collision, but presumably that would be a lot of work to program in and does not seem like it is worth the effort.

**Comment by jbphet** [comment]
@ariel-phet - I'm okay with removing the bonding altogether, but should we take, say, a half hour of design meeting with someone with a lot of expertise in this types of bond formation to brainstorm how we could work it in to the simulation design, and then have me evaluate how much implementation effort it would take?  I'd just like to make sure we don't dismiss the idea of showing a more correct version of the bonding before doing a minimal investigation, since it is a pretty important concept.

**Comment by kathy-phet** [comment]
Emily B writes: 

> I agree with this proposal, and with a few good questions this could be a nice entrée into discussions about energy releases upon bonding.  The problem of not having an energy "receiver" is one I am attempting to solve with my energy & bonding sim.  I'd like to resurrect a discussion on how to fit the development of this sim into your busy schedules!

**Comment by ariel-phet** [comment]
@jbphet I am open to a having a design meeting on the topic. Let me ping Emily B to see if she is free this week.

@kathy-phet @jbphet - part of me is thinking we could do something a little cheesy like have "bond" button. So it acts like everything else, but if you push the bond button you see energy taken away in some way, perhaps with a manufactured collision or such.

**Comment by kathy-phet** [comment]
Joe R responds: 

> This sounds much better. I think it satisfies my concerns.

**Comment by kathy-phet** [comment]
Robert P responds: 

> I agree this the proposal also. It keeps the sim focussed  on the primary goal of understanding the basic energy scales involved in intramolecular forces (“chemical bonds”) vs. intermolecular forces (“van der Waals forces”) and doesn’t give a misleading impression that there is something magical about the latter vs. the former, which could be the case for the sim in its current form. Students come in to introductory chemistry with some quasi-magical ideas like “atoms like to fill their outer shells, hence O-O will make a bond but Ne-Ne won’t”, which are not exactly misconceptions - they are, in fact, ideas that working chemists use all the time - but which get in the way of understanding the underlying physical principles.

**Comment by kathy-phet** [comment]
My inclination is to not work on a "bonding" option at this time. We could keep it as an enhancement option for the future, if resources to support this upgrade become available.

**Comment by jbphet** [comment]
Based on the responses above, I'm thinking I should just implement the non-bonding behavior, and we shouldn't worry about implementing any sort of boding feature at this point.  @ariel-phet - if you're okay with that, I'll move forward on it.

**Comment by kathy-phet** [comment]
Ariel and I had already discussed this and agreed to move forward without the bonding option. So yes, @jbphet, you can move forward with implementing the above proposal. Thanks!

**Comment by jbphet** [comment]
Relevant commit (that I forgot to get in comment): https://github.com/phetsims/states-of-matter/commit/8b5476c386491d8f5ee53fe9bd79cba97378d56c

**Comment by jbphet** [comment]
I tried removing the bonding and leaving the well the same size, but it has a couple of issues:
1. The motion of the marker on the graph is so fast that it aliases, and it's hard to see what is going on
2. The motion of the atoms is so fast that it almost looks like they are bonding
3. The potential levels are so high that I have to reduce the max timestep to prevent the movable atom from flying away, and this may have performance implications (I reduced it a factor of 8 from 0.005 seconds to 0.000625 seconds).

I talked with @ariel-phet and @arouinfar, and both were okay with the idea of doing some "hollywooding" here where we have a well for the oxygen-oxygen case that is much larger than the others, but not as large as in the bonding version.  I have a version working on the remove-o-o-bonding branch with some initial values that look decent to me.  I'll review with @kathy-phet and go from there.

**Comment by jbphet** [comment]
I have created a version that removes the bonding behavior and also reduces the size of the potential well.  I also revised the zoom range to suit the new max potential depth.  The new values for sigma and epsilon were chosen empirically - I don't know enough about what *should* happen to do anything other than that.

Assigning to @kathy-phet, @ariel-phet, @arouinfar to review and comment.  When the three of you have all weighed in, please assign back to me and I'll take it from there.

Link: https://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.1.0-dev.2/phet/atomic-interactions_en_phet.html.

**Comment by arouinfar** [comment]
@jbphet the behavior looks reasonable to me. O-O is still a bit jumpy, particularly on the left side of the well. Viewing the sim in slow motion goes a long way to reduce the jumpiness, so I am not particularly worried that the behavior will be misinterpreted.

**Comment by ariel-phet** [comment]
@jbphet this seems to follow the proposal that was made, and shows a much deeper potential well. I agree with @arouinfar comment above.

@kathy-phet is not going to answer until at minimum next week, so we should just move ahead, I am comfortable making that call, and finishing this off.

**Comment by jbphet** [comment]
Cool - I'll move forward with a release then.

**Comment by arouinfar** [comment]
@jbphet I'm working on updating the teacher tips. Can you ping me when the maintenance release goes live?

**Comment by jbphet** [comment]
The code to remove bonding but still have a deep well has been integrated into master, and all of the bonding code has been removed.

**Comment by KatieWoe** [comment]
@arouinfar something I've noticed in regards to https://github.com/phetsims/atomic-interactions/issues/65#issuecomment-370961339.  The jumpiness on the left side is more noticeable when the total force arrows are used.  Since the atom jumps to slightly different spots each time and the distance between the jumps is larger, the size of the arrows each pass can vary noticeably.  To see this, separate the oxygen atoms slightly so it vibrates; turn on total force; look at the right side of the screen and note how the distance of those arrows varies.

**Comment by arouinfar** [comment]
I'm not noticing an appreciable difference in the oscillation of the atom in the graph with total force on/off for macOS/Chrome. There is a bit of jumpiness in the total force vectors, but I think it's pretty minor. Stepping through the oscillation, the relative magnitude and orientation of the total force vectors seems reasonable to me.

**Comment by jbphet** [comment]
@arouinfar said:

> I'm working on updating the teacher tips. Can you ping me when the maintenance release goes live?

It has gone live.  I'll assign the issue to you, you can work out with @oliver-phet (see below) when to close.

@oliver-phet - there are various points in the dialog above where users opined about the Oxygen-Oxygen behavior.  The version that is now published does not include Oxygen-Oxygen bonding.  I thought you might want to follow up with the folks who were troubled by this behavior to let them know that it has been changed in the sim.

**Comment by arouinfar** [comment]
Thanks @jbphet, I have published the updated teacher tips to the website.

**Comment by jbphet** [comment]
@oliver-phet - I noticed this issue while working on another one in this repo.  Have the people been notified (see https://github.com/phetsims/atomic-interactions/issues/65#issuecomment-553131444) and can this be closed?

**Comment by oliver-phet** [comment]
@jbphet I'll notify Sandor and I just re-read through this issue - who else needs notified?

**Comment by jbphet** [comment]
It looks like there was someone in https://github.com/phetsims/atomic-interactions/issues/68 who expressed concern, and we responded, but it would be good to let them know that we've changed the behavior.

**Comment by oliver-phet** [comment]
I just also emailed the user in https://github.com/phetsims/atomic-interactions/issues/68 that the behavior has been changed. Closing!
