### ISSUE TITLE
Create sim primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/atomic-interactions#67]
Tracking sim primer publication in this issue, so that #59 can be closed.  Assigning to @amyh-phet.

**Comment by arouinfar** [comment]
I'm not sure what else is in your primer queue @amyh-phet, so there's no rush for this primer, in particular. The goal is to close master checklists, so primer publication is being tracked separately.

**Comment by amyh-phet** [comment]
@arouinfar   I'm hoping to get back to primers soon, so I'll add this to the list.

**Comment by amyh-phet** [comment]
Primer completed.
