### ISSUE TITLE
User reported issue: energy conservation

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/atomic-interactions#68]
**Problem description**: scientific misconception?
On of the simulations, that of a di-atomic collision seems to violate energy conservation, unless the (kinetic) energy that is inaccessible to the translation of the nuclei has been transferred to internal degrees of freedom or via radiation. As far as I remember, the latter is unlikely, and the available internal degrees of freedom, electronic states, are not optional channels as well. I suspect that molecular Oxygen is not usually formed from Oxygen radicals. If only Oxygen atoms are present, then probably a 3-atomic collision is necessary to form O2 so that the third atom may carry the excess energy and leave the other two at some vibrational level.

**Steps to reproduce:**
run simulation with the Oxygen + Oxygen to get a molecular bond
Severity: as severe as any energy conservation violation

**Screenshots:**
![image](https://user-images.githubusercontent.com/5090275/26982674-5f655d70-4cf6-11e7-8c04-2f751ede28d9.png)
![image](https://user-images.githubusercontent.com/5090275/26982678-62866da0-4cf6-11e7-8435-cc2adcc313cb.png)

**Comment by amyh-phet** [comment]
@oliver-phet    I think the confusion might be caused by interpreting the sim as modeling collisions between atoms.  The sim is designed to look at factors that influence attraction/repulsion between two atoms but not bond formation that occurs as a result of a collision. The oxygen atoms are assumed to be close enough to each other such that the attractive forces between the two atoms would result in covalent bond formation.  This model does not attempt to show how kinetic energy is transformed into potential energy when two moving oxygen atoms collide and form a covalent bond.

**Comment by oliver-phet** [comment]
Thanks, I'll reply back to the user. Closing for now.

**Comment by oliver-phet** [comment]
Reply from user:

> My point was that it impossible for two free isolated Oxygen atoms to form a molecule. Therefore, even in a model that concentrates on forces, one wouldn't like to imply that such a process may occur.
> In PHET's simulation of the absorption/emission of radiation by a Hydrogen atom, the dynamics takes into account excluded electronic  radiative transitions, although the model that is demonstrated is a simpler one. This is an example of PHET's great achievement - being pedagogically focused while maintaining scientific accuracy. 
> Depicting (even schematically) two Oxygen atoms that approach each other and stick together is a violation of conservation of energy (Forming chemical bonds only lowers potential energy, in contrast with "squeezing a spring".)

**Comment by jbphet** [comment]
Assigning to @ariel-phet to figure out if further followup is needed since  @amyh-phet is leaving.

**Comment by ariel-phet** [comment]
@oliver-phet can you reply to the user and cc me.

Please respond with the following "While we understand that this depiction has some downsides, please note that the oxygen atoms are already "stuck"when the simulation begins. The learning goals of this scenario are focused around the attraction between those atoms once they are already in the potential well minimum. As you stretch the moveable atom away, and then release, it returns to the equilibrium position, and the energy put into the system has been shown as vibration (kinetic energy). You are certainly correct that such a bond would not form from a collision, but this scenario is best thought of as stretching the  bond. And in this depiction, the bond can be "broken" by pulling the moveable atom far enough away. Of course in real life, one could also not "pin" an atom in place (violating the Heisenberg uncertainty principle among plenty of other issues), but we felt it acceptable to take such liberties in this simulation."

**Comment by oliver-phet** [comment]
Reply sent. Closing for now.

**Comment by oliver-phet** [comment]
Just thought I would post the reply from this user after a recent email from https://github.com/phetsims/atomic-interactions/issues/65. I sent the user the old version of the AI.

> Thank you very much for informing me about the update.
> I would like to ask for a favor:
> Would it be possible to send me an executable copy of the old simulation, the one that does contain the bonding of the oxygen atoms? 
> I would like to use it for a seminar I prepare for a course I take in the Hebrew University. The seminar is about scientific values. I find that our interaction:
>  the letter I wrote, you addressing it seriously, the team reviewing the simulation and eventually modifying it in a subsequent version,
>  all genuinely represents the scientific spirit, and exemplifies values of the scientific community.
> Of course I will not distribute the outdated version.
