### ISSUE TITLE
Reset-all button doesn't reset the graph zoom state to start

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#7]
The reset-all button should reset everything to the sim-startup settings, meaning it should also reset the graph to the fully zoomed-in state, identical to when the sim is initially loaded.

**Comment by jbphet** [comment]
Sounds like this may be fixed, assigning to @ycarpenterphet to verify on Looks like this may have been fixed. Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html. If fixed, please close, if not, please assign to @kmsravindra.

**Comment by ycarpenterphet** [comment]
Looks like this is fixed in dev2. Closing.
