### ISSUE TITLE
Query parameter doesn't work for setting projector mode

### ISSUE THREAD

**Issue by jbphet** [phetsims/atomic-interactions#71]
The query parameter `colorProfile=projector` should cause the sim to load with projector mode enabled, but it doesn't work.  This is true on both the currently published version (1.0.5) and the current master version.

**Comment by jbphet** [comment]
Note that it works fine to set projector mode via the "Options" dialog (available in the PhET menu).

**Comment by jbphet** [comment]
I must've messed up this test somehow.  It DOES seem to be broken in the published version, but works fine on master.  I'll move the status to fixed-pending-testing, since it would be good to double check this before we republish.

**Comment by KatieWoe** [comment]
Looks good on 1.1.0-rc.1 on Win 10 chrome.

**Comment by SaurabhTotey** [comment]
Seems to work now in the latest deployed version. Closing.
