### ISSUE TITLE
Sharp vertex in custom attraction

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/atomic-interactions#73]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/216
When using custom attraction, the red line can become very pointed, rather than a curve.  I have not noticed any performance or behavior issues from this, so it is more of a question on the desired appearance of the sim.
**Steps to reproduce:**
1. Choose custom attraction
2. Set diameter as small as possible and strength as high as possible
3. Zoom the graph in as much as possible
4. Move the second out of the way and pause the sim so it does not move back

**Screenshots:**
![pointy](https://user-images.githubusercontent.com/41024075/48863934-53ad4680-ed88-11e8-9320-125750dcc817.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Atomic Interactions‬
URL: https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.1/phet/atomic-interactions_en_phet.html
Version: 1.1.0-rc.1 2018-11-05 21:18:48 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"atomic-interactions":{"sha":"15bb3a2d","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"749f10ff","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"d6317e0b","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Thanks for checking @KatieWoe. The sharp vertex is an artifact of the scaling. For most values, the vertex is appropriately rounded. I don't think it's particularly harmful, and it's is also present in the published version of the sim, so closing.
