### ISSUE TITLE
Usability on a small screen review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/atomic-interactions#78]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Should touchSnag be on the atoms?

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56169177-8a376800-5f9a-11e9-984a-53c0ac71aaad.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56169178-8a376800-5f9a-11e9-9d26-2ab9f2384b3b.png)

**Comment by arouinfar** [comment]
These changes will be handled in https://github.com/phetsims/states-of-matter/issues/243, so closing.
