### ISSUE TITLE
User suggestion: "diatomic molecule diameter"

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/atomic-interactions#81]
> In the "atomic interactions" html5 simulation, when one selects "custom attraction" it is written sigma "atom diameter".
It would be more precise to write sigma "diatomic molecule diameter" because its a molecule.
I can make the same comment for the french translation (I imagine all of them are derived from the original english version)

**Comment by arouinfar** [comment]
Aside from oxygen-oxygen, none of these atoms are actually bonded, so it would be inaccurate to describe them as molecules. The σ parameter is a term in the Lennard-Jones potential (the red curve in the sim). The value of σ in the model is the [Van der Waals radius](https://en.wikipedia.org/wiki/Van_der_Waals_radius) for the non-bonding atomic pairs, and for oxygen-oxygen (the only pair of atoms that actually bonds) the value is the average bond length. The Van der Waals radius is widely used as a measure of atomic radius. For the Custom Attraction option, increasing σ will increase the atomic diameter. 

@oliver-phet can you reply to the user?

**Comment by oliver-phet** [comment]
Replied!

**Comment by arouinfar** [comment]
Thanks!
