### ISSUE TITLE
Pinned and Moving Strings box shrinks in stringTest=long

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/atomic-interactions#82]
**Test device**
Windows 7 personal laptop
**Operating System**
Windows 7 6.1
**Browser**
Chrome 
**Note**
Similar to current bug https://github.com/phetsims/atomic-interactions/issues/74
**Problem description**
From https://github.com/phetsims/QA/issues/385

Atom selection box shrinks significantly when strings are changed. Does not occur in the published version.
**Steps to reproduce**
1. Add query parameter stringTest=long
2. Compare to published version

**Visuals**
Switching between the RC test version and the published version
![2019-10-11StringLongAtmcInt](https://user-images.githubusercontent.com/54685448/66685727-8a0ee100-ec3a-11e9-8d87-4ecfe3ad6afd.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_en.html?stringTest=long
Version: 1.0.16 2019-10-03 15:38:28 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1366x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"atomic-interactions":{"sha":"a90a40fd","branch":"HEAD"},"axon":{"sha":"b4404f00","branch":"HEAD"},"babel":{"sha":"de9c74f5","branch":"master"},"brand":{"sha":"63879db6","branch":"HEAD"},"chipper":{"sha":"b7650b7f","branch":"HEAD"},"dot":{"sha":"23b13772","branch":"HEAD"},"joist":{"sha":"f00375ae","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"nitroglycerin":{"sha":"ad3cb990","branch":"HEAD"},"phet-core":{"sha":"8d3194b7","branch":"HEAD"},"phetcommon":{"sha":"65e594b4","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"c6ed1e57","branch":"HEAD"},"scenery-phet":{"sha":"5f33d513","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"states-of-matter":{"sha":"8ff9bed9","branch":"HEAD"},"sun":{"sha":"10af95af","branch":"HEAD"},"tandem":{"sha":"4a8edbc9","branch":"HEAD"}}

**Comment by SaurabhTotey** [comment]
After reviewing this issue with @jbphet, we decided that this issue was negligible and unlikely to come up. As such, I will close this issue. Thanks for noting it, however, @loganbraywork!
