### ISSUE TITLE
Phet-io atoms not moved in state or launched studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/atomic-interactions#85]
For ES6 Testing.
When a sim is launched from studio when an atom has changed position, the new position isn't reflected in the launched version of the sim. The state wrapper doesn't reflect atom movement either.
![atomlocation](https://user-images.githubusercontent.com/41024075/76118256-b7be4300-5faa-11ea-8973-371f647a2820.gif)
![atomstate](https://user-images.githubusercontent.com/41024075/76118259-b856d980-5faa-11ea-9a4b-4cbec98994c9.gif)

**Comment by jbphet** [comment]
The atoms now move in the state wrapper and are positioned when launched from studio.  Closing.
