### ISSUE TITLE
Appearance of labels in forces menu doesn't match design spec

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/atomic-interactions#9]
(1) The text "Hide Forces" and "Total Force" should be left-aligned with the straight edge of the bracket for the last radio button. 

(2) Slightly decrease the font size for the Attractive and Repulsive labels, in order to increase the spacing between the first two radio buttons.

See this snapshot from the design doc:
![screen shot 2015-02-25 at 7 44 12 pm](https://cloud.githubusercontent.com/assets/4682895/6385424/c8d0fce0-bd26-11e4-9ad6-cf8ff6b25dc6.png)

**Comment by jbphet** [comment]
Sounds like this may be fixed, assigning to @ycarpenterphet to verify on Looks like this may have been fixed.  Assigning to @ycarpenterphet to verify on http://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.0-dev.2/atomic-interactions_en.html.  If fixed, please close, if not, please assign to @kmsravindra.

**Comment by pixelzoom** [comment]
In the commit above (https://github.com/phetsims/atomic-interactions/commit/864d0aa82642326200b8da96472be842bba07b54), magic constants were introduced in AtomicInteractionsControlPanel:

> var sliderTrackWidth = enableHeterogeneousMolecules ? 130 : 120;

Why these particular values? Are these values specific to the English strings, or will they provide the requested layout for all locales?

**Comment by ycarpenterphet** [comment]
@kmsravindra Can you respond to @pixelzoom's comment, above, as to whether the alignment in the latest version allows for i8n support while maintaining this alignment?

**Comment by ChandrashekarBemagoni** [comment]
Removed magic constansts var sliderTrackWidth = enableHeterogeneousMolecules ? 130 : 120;.
Now  force control panel  aliginment is i18n support.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commits. Assigning to @ycarpenterphet for verification

**Comment by ycarpenterphet** [comment]
Looks good. Closing.
