### ISSUE TITLE
Possible to drag force arrows to move atom

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/atomic-interactions#91]
**Test device**
Dell
**Operating System**
Ein 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/575. This does happen in the published sim.
It is possible to drag the force arrows on the moveable atom, rather than the atom itself. As the atom then moves, the arrow changes size, which often leads it to look like you are dragging nothing.
**Steps to reproduce**
1. Pause the sim
2. Turn on one of the force arrow options (I find the attractive/repulsive option easier)
3. Drag the atoms close and make the force arrows large.
4. Grab one of the arrows coming off the moveable atom somewhere it does not overlap with the atom.

**Visuals**

![dragarrows](https://user-images.githubusercontent.com/41024075/101527255-fe323b00-394a-11eb-8db1-4ef2b10c717e.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Atomic Interactions‬
URL: https://phet-dev.colorado.edu/html/atomic-interactions/1.2.0-rc.2/phet/atomic-interactions_en_phet.html
Version: 1.2.0-rc.2 2020-11-02 21:58:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
I've addressed this by setting `pickable` to `false` for the force arrows.

**Comment by KatieWoe** [comment]
Looks good in 1.2.0 rc.3
